# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    
    - name: Checkout tools repo
      continue-on-error: true
      uses: actions/checkout@v2
      with:
        repository: apache/Avro
        path: ./my-tools
        fetch-depth: 0
        ref: release-1.8.0
    
    
    - name: fetch  
      continue-on-error: true
      run: git fetch
      working-directory: ./my-tools

    - name: execute
      run: java -Xmx2g -jar ./target/DesigniteJava.jar -i ./my-tools/ -o ./
    
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: DesigniteJava.jar
        # A file, directory or wildcard pattern that describes what to upload
        path: ./target/DesigniteJava.jar


